// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 15,
    fontFamily:
      'FuraMonoNerdFontComplete-Regular, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: "#bcdfda",
    cursorAccentColor: "#000",
    cursorShape: "BEAM",
    cursorBlink: false,
    foregroundColor: "#fff",
    backgroundColor: "#1e2024",
    selectionColor: "rgba(248,28,229,0.3)",
    borderColor: "#333",
    css: "",
    termCSS: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "12px 14px",
    // colors: {
    //   black: '#000000',
    //   red: '#C51E14',
    //   green: '#1DC121',
    //   yellow: '#C7C329',
    //   blue: '#0A2FC4',
    //   magenta: '#C839C5',
    //   cyan: '#20C5C6',
    //   white: '#C7C7C7',
    //   lightBlack: '#686868',
    //   lightRed: '#FD6F6B',
    //   lightGreen: '#67F86F',
    //   lightYellow: '#FFFA72',
    //   lightBlue: '#6A76FB',
    //   lightMagenta: '#FD7CFC',
    //   lightCyan: '#68FDFE',
    //   lightWhite: '#FFFFFF',
    // },
    shell: "",
    shellArgs: ["--login"],
    env: {},
    bell: "SOUND",
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
  },

  plugins: [
    "hyperlinks",
    "hyperpower",
    "hypergoogle",
    "hyperterm-tabs",
    "hyperterm-paste",
    "hyper-hide-scroll",
    "hyper-drop-file",
    // "hyper-subliminal-theme",
    // "hyper-dracula",
    // "hyper-whimsy",
    "hyper-rose-pine",
    "hyper-final-say",
  ],
  localPlugins: ["fig-hyper-integration"],
  keymaps: {
    // Example
    // 'window:devtools': 'cmd+alt+o',
  },
};
